dist: trusty

sudo: true

language: node_js

node_js:
  - '8.11.3'

before_install:
  - npm install -g codecov

script:
  - node -v
  - gradle sapientAllStart -Ptest.mode=local -Ptest.output=true
  - cd Sapient/
  - codecov
  - mv ./coverage ..
