dist: trusty

sudo: true

language: node_js

node_js:
  - '8.11.3'

script:
  - node -v
  - gradle sapientAllStart -Ptest.mode=local -Ptest.output=true --info --debug

after_success:
  - bash <(curl -s https://codecov.io/bash)
