dist: trusty

sudo: true

language: node_js

git:
   depth: 9999999

node_js:
  - '8.11.3'

before_install:
  - npm install -g codecov

script:
  - node -v
  - cd Sapient/
  - ng test --watch false --code-coverage
  - codecov
  - mv ./coverage ..

before_deploy:
  - cd ../sapient-server
  
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true