dist: trusty

sudo: true

language: node_js

git:
   depth: 9999999

node_js:
  - '8.11.3'

before_install:
  - npm install -g codecov

script:
  - node -v
  - gradle sapientAllStart -Ptest.mode=local -Ptest.output=true
  - cd sapient-server/
  - npm install
  - npm run test-cover
  - mv ./coverage ./coverage-server
  - mv ./coverage-server ..
  - cd ..
  - cd Sapient/
  - ng test --watch false --code-coverage
  - codecov
  - mv ./coverage ..
  - cd ..