dist: trusty

sudo: true

language: node_js

node_js:
  - '8.11.3'

before_install:
  - npm install -g codecov

script:
  - node -v
  - gradle sapientAllStart -Ptest.mode=local -Ptest.output=true
  - cd Sapient/
  - ng test --watch false --code-coverage
  - codecov
  - mv ./coverage ..

before_deploy:
  - cd .. 
  - cd ..
  - cd sapient-server
  
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true