dist: trusty

sudo: true

language: node_js

node_js:
  - '8.11.3'

before_install:
  - pip install --user codecov
script:
  - node -v
  - gradle sapientAllStart -Ptest.mode=local -Ptest.output=true --info --debug
  - cd Sapient/
  - npm run test
after_success:
  - codecov
